# Install provider-kubernetes in the cluster (use this instead of the repo's crossplane.yaml).
# The repo's crossplane.yaml uses meta.pkg.crossplane.io/v1 (package definition), which is not
# for installation. Crossplane Helm installs the pkg.crossplane.io/v1 CRDs; use this manifest.
#
# Apply: kubectl apply -f crossplane/provider-kubernetes-install.yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-kubernetes:v1.2.0
